In [8]:
# Import libraries
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import random

In [9]:
class MontyHall:
    switch_games = []
    stay_games = []
    
    def __init__(self, num_trials):
        self.num_trials = num_trials
        self.simulate_games()
    
    def simulate_game(self, does_switch):
        winning_door = random.randint(1, 3)
        initial_pick = random.randint(1, 3)
        monte_doors = [1, 2, 3]
        # remove the winning door and inital pick from options that monte can reveal
        monte_doors.remove(winning_door)
        if initial_pick != winning_door: monte_doors.remove(initial_pick)
        monte_opens = random.choice(monte_doors)

        # case of switching    
        if does_switch:
            doors = [1, 2, 3]
            doors.remove(initial_pick)
            doors.remove(monte_opens)
            # the remaining door        
            switch_pick = doors[0]

            if switch_pick == winning_door:
                return 1
            else:
                return 0
        # case for not switching
        elif initial_pick == winning_door: 
            return 1
        else:
            return 0

    def simulate_games(self):
        for trial in range(self.num_trials):
            self.switch_games.append(self.simulate_game(True))
            self.stay_games.append(self.simulate_game(False))

In [10]:
# run the simulation
game = MontyHall(10000)

In [11]:
# mean of switching
np.mean(game.switch_games)


0.6734

In [12]:
# mean of staying
np.mean(game.stay_games)

0.3264

In [13]:
# variance of switching
np.var(game.switch_games)

0.21993244

In [14]:
# variance of staying
np.var(game.stay_games)

0.2198630400000001

Conclusions
The following conclusions are based on a simulation of 10,000 games. The mean rate of success for switching is 67.34 percent versus 32.64 percent for staying. Both stratagies exhibited similar variances of 0.219. With these results the recommended strategy is to switch the guess.